### ISSUE TITLE
DAT落ちのスレの取得時に「★5chからのお知らせ」を経由してしまい、閲覧履歴にも残る

### ISSUE THREAD

**Issue by cyatarow** [nonnonstop/apimater#3]

**Comment by nonnonstop** [comment]
Since ChMate has a dat cache of the last opened thread, the app will open another thread before the original one.

In the previous version, it cleared the memory cache by killing the ChMate process. However, this does not work well in newer versions of Android.
To revert to the behavior of the previous version, change the viewer script to the following:
```javascript
function view(activity, htmlUrl) {
    var viewer = Packages.com.nonnonstop.apimate.viewer.BuiltinViewer();
    viewer.view(activity);
}
```

**Comment by cyatarow** [comment]
It works fine. Thank you for the script.
